version: "3.9"

services:
  web:
    image: devsecops-aws-app:ci
    build: ./app
    container_name: devsecops-aws-app
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
