version: "3.9"

services:
  web:
    image: devsecops-aws-app:ci
    build: ./app
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - BUILD_ID=${BUILD_ID}
    restart: unless-stopped
