name: CI - Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose Build
        run: |
          docker compose build --no-cache

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: devsecops-aws-app:ci
          scanners: vuln
          vuln-type: os,librery
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Docker Compose Up (smoke test)
        run: |
          docker compose up -d
          sleep 5

      - name: Docker Compose Down
        run: |
          docker compose down
