name: CD - Production Like Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # pull the code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Setup SSH
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.EC2_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> "$HOME/.ssh/known_hosts" || true

      # sync app
      - name: Sync application to server
        run: |
          rsync -avz --delete \
            --exclude infra \
            --exclude .git \
            --exclude node_modules \
            ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}

      # restart container
      - name: Restart containers
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/deploy/DevSec-Project
            docker compose up -d --build
          EOF
